spring.application.name=codepilot-backend

# Server
server.port=8080

# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ===============================
# NVIDIA Nemotron
# ===============================
nemotron.base-url=${NEMOTRON_BASE_URL}
nemotron.api-key=${NEMOTRON_API_KEY}
nemotron.model=${NEMOTRON_MODEL}

#ai.embedding.provider=nemotron
#ai.embedding.api-key=${NEMOTRON_API_KEY}
#ai.embedding.base-url=${NEMOTRON_BASE_URL}
#ai.embedding.model=${NEMOTRON_MODEL}

ai.embedding.provider=gemini
ai.embedding.api-key=${GEMINI_API_KEY}