package com.codepilot.edit.service;

import com.codepilot.edit.dto.ApplyEditsRequest;
import com.codepilot.repo.dto.EditDeliveryResult;
import com.codepilot.repo.dto.SourceType;
import com.codepilot.repo.entity.CodeRepositoryEntity;
import com.codepilot.repo.service.GitCommitService;
import com.codepilot.repo.service.GitHubApiClient;
import com.codepilot.repo.service.RepositoryRegistryService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Decides HOW an approved edit reaches its destination, based on where the repository came
 * from. The edit itself - matching SEARCH blocks, rewriting files, backups, rollback - stays
 * entirely in EditApplier. This class only routes.
 *
 *   LOCAL  : write to the user's folder, exactly as before.
 *   GITHUB : branch, apply, commit, push, open a pull request. main is never touched.
 *
 * Why GITHUB cannot simply write to disk: that clone is CodePilot's scratch copy, and
 * RepositoryRegistryService.sync does a HARD RESET. An edit left sitting in the working
 * directory would be destroyed by the next fetch, silently and with no warning.
 */
@Service
public class EditDeliveryService {

    private static final Logger log = LoggerFactory.getLogger(EditDeliveryService.class);

    private final RepositoryRegistryService registry;
    private final EditApplier editApplier;
    private final GitCommitService commitService;
    private final GitHubApiClient gitHubApiClient;

    public EditDeliveryService(RepositoryRegistryService registry,
                               EditApplier editApplier,
                               GitCommitService commitService,
                               GitHubApiClient gitHubApiClient) {
        this.registry = registry;
        this.editApplier = editApplier;
        this.commitService = commitService;
        this.gitHubApiClient = gitHubApiClient;
    }

    /**
     * @param repositoryId a registered repository
     * @param edits        what the user approved
     * @param instruction  the user's original request, used for the branch name, commit
     *                     message and pull request title
     */
    public EditDeliveryResult deliver(UUID repositoryId,
                                      List<ApplyEditsRequest.ApprovedEdit> edits,
                                      String instruction) {

        CodeRepositoryEntity repository = registry.require(repositoryId);
        String root = repository.getLocalPath();

        log.info("Delivering {} edit(s) to {} repository '{}'",
                edits.size(), repository.getSourceType(), repository.getName());

        if (repository.getSourceType() == SourceType.LOCAL) {
            EditApplier.ApplyResult result = editApplier.apply(root, edits);
            return EditDeliveryResult.local(result.changedFiles(), result.backupLocation());
        }

        return deliverToGithub(repository, root, edits, instruction);
    }

    private EditDeliveryResult deliverToGithub(CodeRepositoryEntity repository, String root,
                                               List<ApplyEditsRequest.ApprovedEdit> edits,
                                               String instruction) {

        Path directory = Path.of(root);
        String baseBranch = repository.getBranch();

        if (baseBranch == null || baseBranch.isBlank()) {
            throw new IllegalStateException(
                    "Repository '" + repository.getName() + "' has no recorded branch. "
                            + "Sync it before applying edits.");
        }

        // Branch FIRST, then edit. Creating the branch afterwards would also work, but this
        // ordering means an EditApplier failure leaves the base branch's working tree
        // untouched, and the only cleanup needed is checking the branch back out.
        String branch = commitService.createBranch(directory, instruction);

        try {
            EditApplier.ApplyResult result = editApplier.apply(root, edits);

            // Commits ONLY the files EditApplier reports as changed - never "git add .".
            // EditApplier writes backups into root/.codepilot-backups/, so a blanket add
            // would put a full copy of every original file into the pull request.
            Optional<String> commitSha = commitService.commitFiles(
                    directory,
                    result.changedFiles(),
                    "CodePilot: " + instruction + "\n\nGenerated by CodePilot AI.");

            if (commitSha.isEmpty()) {
                // No diff: the edits were already present. Report it honestly rather than
                // pushing an empty branch and opening a pull request with nothing in it.
                log.info("No changes to commit for '{}' - reporting no-op", instruction);
                return EditDeliveryResult.noChanges();
            }

            commitService.push(directory, branch);

            String prUrl = gitHubApiClient.createPullRequest(
                    repository.getRemoteUrl(),
                    branch,
                    baseBranch,
                    "CodePilot: " + instruction,
                    pullRequestBody(instruction, result.changedFiles()));

            return EditDeliveryResult.github(result.changedFiles(), branch, commitSha.get(), prUrl);

        } finally {
            // ALWAYS return the clone to its base branch.
            //
            // Left sitting on a feature branch, the next sync's hard reset targets the wrong
            // ref, and the state of this directory then depends on whatever happened last
            // time - the kind of hidden statefulness that makes a failure impossible to
            // reproduce.
            //
            // This runs after the commit rather than instead of it because a checkout with
            // uncommitted changes present would fail. If EditApplier threw, nothing was
            // written and the checkout is clean; if the commit succeeded, the tree is clean
            // too. The one gap is a failure between applying and committing, which is why
            // this is logged rather than swallowed.
            try {
                commitService.checkout(directory, baseBranch);
            } catch (RuntimeException e) {
                log.warn("Could not return {} to branch {} - the clone is left on a feature "
                                + "branch and the next sync may behave unexpectedly: {}",
                        directory, baseBranch, e.getMessage());
            }
        }
    }

    /**
     * The pull request description. Two things it must do: say what was asked for in the
     * user's own words, and make unmistakably clear that a language model wrote the diff.
     */
    private String pullRequestBody(String instruction, List<String> changedFiles) {
        String fileList = changedFiles.stream()
                // Git and GitHub both use forward slashes; EditApplier reports Windows paths
                // with backslashes, which would render as escapes inside markdown backticks.
                .map(path -> "- `" + path.replace('\\', '/') + "`")
                .reduce((a, b) -> a + "\n" + b)
                .orElse("_(none)_");

        return """
               ## Requested change

               %s

               ## Files modified

               %s

               ---
               Generated by **CodePilot AI**. **Review before merging** - these changes were
               produced by a language model and have not been compiled or tested.
               """.formatted(instruction, fileList);
    }
}